### ISSUE TITLE
Feature request: Support for additional types

### ISSUE THREAD

**Issue by FrediBach** [hasura/json2graphql#2]
The current version supports int, float, text and boolean. It would be nice if more types could be auto detected. Here's a list of the most important ones that would be helpful for building real world apps:

Date: `"1996-03-15"`
Timestamp: `"2016-07-20T17:30:15+05:30"`
JSON: `{mykey: "something"}`

Date and timestamp should be fairly easy to detect with Regex pattern matching and JSON detection could be done with JSON.parse in a try/catch statement guess.

I've added a sample JSON that contains all three types in this gist, so you have something to test with: https://gist.github.com/FrediBach/1fc457f73f11864e0ff1839bde835b83

**Comment by FrediBach** [comment]
Oh and additionally, as you could guess from the sample data, if we could support geometric types officially and not just by having lat, lng and radius fields, that would be even better, so that you could filter with them inside a query. :-)

**Comment by wawhal** [comment]
@FrediBach I have kind of implemented this in [this branch](https://github.com/hasura/json-data-import/tree/issue-2). Support for Data and JSON has been added.

1. Any kind of `Date` object will be added as `timestamp with timezone` type.
2. If the value of any key is an object, it'll be assigned the type JSON and the object will be stringified before inserting

(1) is fine.

About (2), if this is merged, we won't be able to do things like [this](https://github.com/hasura/json-data-import/issues/4). Because anything that's nested is a potential JSON typed data. Of course, we can hack around by having different naming conventions. But I think that'll be a bit too much.

Tell me what you think.

**Comment by splodingsocks** [comment]
I'll put a vote in for arrays of simple types as well. I'm currently trying to use a `text[]` and it'd be great if Hasura would put that in the schema as a `[String!]!` instead of `_text`, which it is at the moment.

**Comment by FrediBach** [comment]
Hmm, good input about multi relationships. Have to think about a nice solution, currently I don't have a clean one.

**Comment by FrediBach** [comment]
Ok, I think the best solution would be:

```
users: [
    { id: 1, username: 'user1', user_ids: [2, 3] },
    { id: 2, username: 'user2', user_ids: [1] },
    { id: 3, username: 'user3', user_ids: [] },
    { id: 4, username: 'user4', user_ids: [1, 2, 3] },
]
```
We already have the `_id` naming convention for single relationships, so using `_ids` would be the logical solution for multiple.

And we could always combine this with the named key idea like this:

```
users: [
    { id: 1, username: 'user1', friends__user_ids: [2, 3] },
    { id: 2, username: 'user2', friends__user_ids: [1] },
    { id: 3, username: 'user3', friends__user_ids: [] },
    { id: 4, username: 'user4', friends__user_ids: [1, 2, 3] },
]
```

**Comment by wawhal** [comment]
Repo has been moved. This issue is tracked [here](https://github.com/hasura/graphql-engine/issues/466).
